name: ci

on:
  push:
    branches: v2.0

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push alert server
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          push: true
          tags: ghcr.io/bgdsh/dolphinscheduler:2.0.5
     